applicationName: CWDS API
version: ${APP_VERSION:-local}

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro.ini}"]
  
swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS API
  description: RESTful API definitions for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png
  loginUrl: ${LOGIN_URL:-http://localhost:8090/authn/login}
  showSwagger: ${SHOW_SWAGGER:-false}
  jsonUrl: ${SWAGGER_JSON_URL:-http://localhost:8080/swagger.json}
  callbackUrl: ${SWAGGER_CALLBACK_URL:-http://localhost:8080/swagger}

nsDataSourceFactory:
  driverClass: org.postgresql.Driver
  user: ${DB_NS_USER}
  password: ${DB_NS_PASSWORD}
  url: ${DB_NS_JDBC_URL}
  validationQuery: "/* MyService Health Check */ SELECT 1"
  logValidationErrors: true
  initialSize: ${DB_NS_CP_INITIAL_SIZE:-2}
  minSize: ${DB_NS_CP_MIN_SIZE:-2}
  maxSize: ${DB_NS_CP_MAX_SIZE:-8}
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate.id.new_generator_mappings: false
      hibernate.show_sql: true


cmsDataSourceFactory:
  autoCommitByDefault: false
  driverClass: com.ibm.db2.jcc.DB2Driver
  user: ${DB_CMS_USER}
  password: ${DB_CMS_PASSWORD}
  url: ${DB_CMS_JDBC_URL}
  validationQuery: "/* MyService Health Check */ SELECT 1 FROM sysibm.sysdummy1 for read only"
  logValidationErrors: true
  initialSize: ${DB_CMS_CP_INITIAL_SIZE:-2}
  minSize: ${DB_CMS_CP_MIN_SIZE:-2}
  maxSize: ${DB_CMS_CP_MAX_SIZE:-8}
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.show_sql: true
      hibernate.default_schema: ${DB_CMS_SCHEMA}
      hibernate.connection.autocommit: false

elasticsearch:
  elasticsearch.host: ${ES_HOST:-es.dev.cwds.tabordasolutions.net}
  elasticsearch.port: ${ES_PORT:-9300}
  elasticsearch.cluster: ${ES_CLUSTER:-taborda-dev-es}
  elasticsearch.alias: ${ES_ALIAS:-people}
  elasticsearch.doctype: ${ES_DOCTYPE:-person}
  
smartystreets:
  clientId: ${SS_ID:-8721f357-6381-1001-4633-5157e84b68cb}
  token: ${SS_TOKEN:-Q62NxpgzuBEUq3IalqVx}
  maxCandidates: ${SS_MAX:-10}
  
triggertables:
  laCountySpecificCode: 19
 
webSecurity:
  httpResponseSecurityHeaders:
    # Prevent MIMI sniffing
    X-Content-Type-Options: nosniff
    
    # Prevent click-jacking
    X-Frame-Options: deny
    
    # Prevent cross site scripting
    X-XSS-Protection: 1; mode=block
    
    # Prevent everything other than same origin
    Content-Security-Policy: default-src 'self' 'unsafe-inline';
     
server:
  applicationConnectors:
  - type: http 
    port: ${APP_STD_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${APP_ADMIN_PORT:-8081}
    
  requestLog:
    appenders:
      - type: console

logging:
  level: ${LOGLEVEL:-WARN}
  loggers:
    "org.hibernate.SQL":
      level: DEBUG
    "org.hibernate.type.descriptor.sql":
      level: DEBUG
    "AUDIT":
      level: ALL
    "gov.ca.cwds":
      level: DEBUG    
  appenders:
    - type: console
      threshold: ${LOGLEVEL:-WARN}
      timeZone: UTC
      target: stdout
      logFormat: '%X{remoteAddress} [%date{ISO8601}] %level "%thread" "%X{uniqueId}" %logger: "%message%n"' 